rustbase/rustbase

- .github/workflows/rust.yml
Creates a github action for rust unit tests.
> ci(.github/workflows): github action for unit tests

- .github/workflows/sonarcloud.yml
- sonar-project.properties
A file with SonarCloud configuration and the sonarcloud.yml
> ci: sonarcloud added

- src/db/storage/types.rs
- src/main.rs
Added String, Float, Integer, Boolean, Array, Date and Hash types
> feat: database types

- .github/workflows/rust.yml
set test-thread to 1 on rust.yml workflows
> ci(rust.yml): set `test-threads=1`

- src/db/sharding/unsharding_document.rs
- src/db/storage/read.rs
Added a conditional that unshard document on order
> fix: fix shuffle read document bug

- src/db/database.rs
- src/db/sharding/unsharding_document.rs
Added a unit test on `./src/db/database.rs`
> test(database.rs): added unit tests for database module

- src/db/database.rs
- src/db/storage/document.rs
- src/db/storage/mod.rs
- src/db/storage/types.rs
- src/db/storage/write.rs
Added a new feature and a unit tests for it.
> feat: write documents

- CONTRIBUTE.md
- README.md
> docs: contribute

- Cargo.lock
- Cargo.toml
- src/db/database.rs
- src/db/sharding/sharding_document.rs
- src/db/sharding/unsharding_document.rs
- src/db/storage/README.md
- src/db/storage/document.rs
- src/db/storage/mod.rs
- src/db/storage/read.rs
- src/db/storage/types.rs
- src/db/storage/write.rs
- src/main.rs
> perf: switch json data to bson

- src/crypto/decrypt.rs
- src/crypto/encrypt.rs
- src/crypto/generate_bytes.rs
- src/crypto/hash.rs
- src/db/database.rs
- src/db/mod.rs
- src/db/sharding/sharding_collection.rs
- src/db/sharding/unsharding_collection.rs
- src/db/storage/collection.rs
- src/db/storage/read.rs
- src/main.rs
- src/utils/config.rs
Refactor all code using clippy
> refactor: use clippy linter

- .github/workflows/rust-clippy.yml
Added clippy code analyzer on workflow
> ci(rust-clippy): added clippy workflow

- Cargo.lock
- Cargo.toml
> fix: rand_core updated to 0.6.1

- src/db/database.rs
Added a function that check if bson is array of documents or a single document.
> fix: collection bson

- src/db/database.rs
- src/db/storage/collection.rs
Added a function that add a document to a collection
> feat: create document/documents

- .gitignore
- src/main.rs
- src/utils/config.rs
Change `./data/config.json` to `./rustbase/config.json`
> fix: database path configuration

- CONTRIBUTING.md
- README.md
> docs: fixing contributing

- .gitignore
- src/main.rs
- src/utils/config.rs
Revert `fix: database path configuration`
> revert: database path configuration

- src/db/database.rs
Return document when create a document.
> fix(database.rs): return data

- src/db/database.rs
- src/db/storage/document.rs
Added a function that search a document with a `id`
> feat: get document

- README.md
Change img source link, and authors table
> docs: change img src and authors

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/server/cache.rs
- src/server/main.rs
- src/server/mod.rs
- src/spec.rs
Add `cache` to improve more performance
> feat: add cache

- .github/workflows/release.yml
- .gitignore
- scripts/release.sh
Adds a workflow to add release automatically.
> ci: release github workflow

- .cargo/config.toml
- Cargo.toml
- proto/rustbase.proto
- src/build.rs
- src/main.rs
- src/query/README.md
- src/query/grammar/rustbase.pest
- src/query/mod.rs
- src/query/parser.rs
- src/server/cache/README.md
- src/server/cache/mod.rs
- src/server/engine/README.md
- src/server/engine/mod.rs
- src/server/main.rs
- src/server/mod.rs
- src/server/route/README.md
- src/server/route/mod.rs
> feat: server query

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- README.md
- scripts/release.sh
> feat: windows support

- Cargo.lock
- Cargo.toml
- src/config/mod.rs
- src/config/schema.rs
- src/query/grammar/rustbase.pest
- src/query/parser.rs
- src/server/engine/mod.rs
- src/server/main.rs
- src/utils/crypto.rs
- src/utils/mod.rs
Adding a feature that the request passes to a queue that workers process in a thread
> Feature: Workers

- Cargo.lock
- Cargo.toml
- src/config/README.md
- src/config/mod.rs
- src/config/schema.rs
- src/main.rs
- src/server/auth.rs
- src/server/main.rs
- src/server/wirewave/README.md
- src/server/wirewave/server.rs
TLS/SSL support and `basic` authentication
> feat(wirewave): tls and auth support
